import express from 'express';
import cors from 'cors';
import connect from '../../db/mongoose';
import route from './Route/route';
import swaggerRouter from './Route/swaggerRoute';
connect();
const app = express();
app.use(cors());
app.use(express.json());
app.use(route);
app.use('/', swaggerRouter);
export default app;
